# Setup
title:        Oiva Consulting
tagline:      A brief summary of our services
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Marko Halonen
  url:        http://www.oivakonsultointi.fi 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
